"""
    add_col!(
        df::DataFrame;
        col::String,
        value::Union{Nothing,String},
    )::Nothing

Add a constant-valued column to a `DataFrame` if the column does not already exist.

If `col` is already present in `df`, the function leaves the existing column
unchanged. When a non-`nothing` value is supplied in this situation, a warning is
emitted indicating that the existing column will be used instead of the provided
value.

If the column does not exist, a value must be supplied. The column name and value
are validated for illegal strings before a new column is created and populated with
the specified value for all rows.

# Arguments

- `df::DataFrame`: DataFrame to modify.
- `col::String`: Name of the column to add.
- `value::Union{Nothing,String}`: Value to assign to all rows of the new column.
  Must not be `nothing` when the column does not already exist.

# Returns

- `Nothing`: The input `DataFrame` is modified in place.

# Throws

- `ErrorException`: If the column does not exist and `value` is `nothing`.
- `ErrorException`: If the column name or value contains illegal strings.

# Warnings

- A warning is emitted when `col` already exists and a non-`nothing` value is
  supplied, as the provided value is ignored.

# Notes

- The function performs in-place modification and does not return the modified
  `DataFrame`.
- Existing columns are never overwritten.
- Both the proposed column name and value are validated using
  `check_illegal_strings` before insertion.

# Examples

```jldoctest; setup=:(using GenomicBreedingCore, GenomicBreedingIO, GenomicBreedingDB, DataFrames, CSV, StatsBase, LibPQ, Dates)
julia> simulate_genomes() |> simulate_trials;

julia> df = load_trial_df("simulated_trials.tsv");

julia> p = ncol(df);

julia> add_col!(df, col="some_new_column", value="Dolorem ipsum")

julia> p < ncol(df)
true
```
"""
function add_col!(df::DataFrame; col::String, value::Union{Nothing,String})::Nothing
    # df = CSV.read(simulate_trial(), DataFrame); col = "species"; value = nothing
    # df = CSV.read(simulate_trial(), DataFrame); col = "species"; value = "Lolium multiflorum"
    if col ∈ names(df)
        if !isnothing(value)
            @warn("Using \"$col\" col in the dataframe instead of the supplied \"$col = $value\".")
        end
    else
        if isnothing(value)
            error("Please define the value to be inserted into the \"$col\" column of the dataframe.")
        end
        try
            check_illegal_strings([col, value])
        catch e
            new_error =
                join(["Illegal string/s in new column name [$col] and/or its value [$value]!\n", sprint(showerror, e)])
            error(new_error)
        end
        df[!, col] .= value
    end
    nothing
end

"""
    parse_layouts!(
        df::DataFrame;
        is_trial::Bool=true,
    )::Nothing

Parse layout-related columns into integer values and generate a standardised
`layouts` column.

The function converts the `replications`, `blocks`, `rows`, and `cols` columns to
`Int64` values when they are not already stored as integer vectors. Parsing is
performed by extracting the trailing numeric component from strings containing
underscore- or hyphen-delimited identifiers.

After parsing, a composite `layouts` column is generated by concatenating the
replication, block, row, and column values using the format
`"<replication>-<block>-<row>-<col>"`.

# Arguments

- `df::DataFrame`: DataFrame containing layout-related columns.
- `is_trial::Bool=true`: If `true`, validate the input using `validate_trials`
  before parsing.

# Returns

- `Nothing`: The input `DataFrame` is modified in place.

# Throws

- `ErrorException`: If any of the layout columns cannot be parsed into `Int64`
  values.

# Notes

- The columns `replications`, `blocks`, `rows`, and `cols` are expected to be
  present in the input `DataFrame`.
- Columns already stored as `Vector{Int64}` are left unchanged.
- String values are parsed by extracting the final token after splitting on `_`
  and then `-`.
- A new or updated `layouts` column is created from the parsed integer values.
- The function performs all modifications in place.

# Examples

```jldoctest; setup=:(using GenomicBreedingCore, GenomicBreedingIO, GenomicBreedingDB, DataFrames, CSV, StatsBase, LibPQ, Dates)
julia> df_ids = DataFrame(entries=repeat([""],3), measurements=repeat([""],3), populations=repeat([""],3), seasons=repeat([""],3), sites=repeat([""],3), years=repeat([""],3));

julia> replications=[1, 2, 3]; blocks=[1, 1, 2]; rows=[1, 2, 3]; cols=[10, 11, 12];

julia> df_expected = hcat(df_ids, DataFrame(replications=replications, blocks=blocks, rows=rows, cols=cols, layouts=string.(replications, "-", blocks, "-", rows, "-", cols)));

julia> df_1 = copy(df_expected);

julia> parse_layouts!(df_1)

julia> df_1 == df_expected
true

julia> df_input = hcat(df_ids, DataFrame(replications=["rep_1", "rep_2", "3"], blocks=["b_1", "1", "block-2"], rows=[1, 2, 3], cols=["column-10", "COL-11", "column_12"]));

julia> df_2 = copy(df_input);

julia> parse_layouts!(df_2)

julia> df_2 == df_expected
true
```
"""
function parse_layouts!(df::DataFrame; is_trial::Bool = true)::Nothing
    is_trial ? validate_trials(df) : nothing
    for f in [:replications, :blocks, :rows, :cols]
        # f = :replications
        isa(df[!, f], Vector{Int64}) ? continue : nothing
        df[!, f] = try
            df[!, f] |>
            x ->
                [split(xi, "_")[end] for xi in x] |> x -> [split(xi, "-")[end] for xi in x] |> x -> [parse(Int64, xi) for xi in x]
        catch
            error("Cannot parse $(f)!")
        end
    end
    df.layouts = string.(df.replications, "-", df.blocks, "-", df.rows, "-", df.cols)
    nothing
end

"""
    add_measurement_dates!(
        df::DataFrame;
        measurement_dates::Union{Nothing,Dict{String,String}}=nothing,
    )::Nothing

Add or validate a `dates` column for measurement records in a trial `DataFrame`.

If a `dates` column already exists, the function validates that all date values are
in a recognised date format. When `measurement_dates` is supplied in this case, the
existing `dates` column takes precedence and a warning is emitted.

If no `dates` column exists, dates are derived from the `measurements` column. When
`measurement_dates` is not provided, measurement names are assumed to represent dates
directly and are parsed into `Date` values. When `measurement_dates` is supplied, it
is used to map measurement identifiers to their corresponding dates.

A new `dates` column is added to the input `DataFrame` when required.

# Arguments

- `df::DataFrame`: DataFrame containing measurement records.
- `measurement_dates::Union{Nothing,Dict{String,String}}=nothing`: Optional mapping
  between measurement identifiers and date strings in `yyyy-mm-dd` format.

# Returns

- `Nothing`: The input `DataFrame` is modified in place.

# Throws

- `ErrorException`: If neither a `dates` column nor a `measurements` column is
  available.
- `ErrorException`: If one or more date values are not in the required
  `yyyy-mm-dd` format.
- `ErrorException`: If a measurement defined in `measurement_dates` cannot be found
  in the DataFrame.
- `ErrorException`: If dates are not supplied for all measurements present in the
  DataFrame when using `measurement_dates`.

# Warnings

- A warning is emitted when both a `dates` column and `measurement_dates` are
  provided, as the existing `dates` column is used.

# Notes

- Date strings are expected to follow the `yyyy-mm-dd` format.
- When a `dates` column is already present, only validation is performed.
- Non-string measurement identifiers are converted to `String` before processing.
- All unique measurements must have a corresponding entry in
  `measurement_dates` when a mapping is supplied.
- The function performs all modifications in place.

# Examples

```jldoctest; setup=:(using GenomicBreedingCore, GenomicBreedingIO, GenomicBreedingDB, DataFrames, CSV, StatsBase, LibPQ, Dates)
julia> simulate_genomes() |> simulate_trials;

julia> df = load_trial_df("simulated_trials.tsv"); 

julia> measurements = String.(unique(df.measurements));

julia> measurement_dates::Dict{String,String} = Dict(); [measurement_dates[x] = x for x in measurements];

julia> df_1 = deepcopy(df); df_2 = deepcopy(df);

julia> add_measurement_dates!(df_1);

julia> add_measurement_dates!(df_2, measurement_dates=measurement_dates);

julia> isa(df_1.dates, Vector{DateTime})
true

julia> df_1.dates == df_2.dates
true
```
"""
function add_measurement_dates!(df::DataFrame; measurement_dates::Union{Nothing,Dict{String,String}} = nothing)::Nothing
    # df = CSV.read(simulate_trial(), DataFrame); measurement_dates::Union{Nothing, Dict{String, String}} = nothing
    # df = CSV.read(simulate_trial(), DataFrame); df[!, "dates"] = String.(df.measurements); measurement_dates::Union{Nothing, Dict{String, String}} = nothing
    # df = CSV.read(simulate_trial(), DataFrame); measurement_dates::Union{Nothing, Dict{String, String}} = Dict(); [measurement_dates[x] = x for x in unique(df.measurements)]
    if "dates" ∈ names(df)
        if !isnothing(measurement_dates)
            @warn("Using the \"dates\" col in the dataframe.")
        end
        dates = unique(df.dates) # dates[1] = "2025/JA/01"
        if !isa(dates, Vector{DateTime}) && (sum(.!validate_date.(dates)) > 0)
            error(
                "Invalid date format/s: [\"$(join(dates, "\", \""))\"]. We expect \"yyyy-mm-dd\" format, where all values are integers.",
            )
        end
    else
        if "measurements"∉names(df)
            error(
                "SInce there is no \"dates\" column in the dataframe we expect a \"measurements\" column instead which we can parse into dates of use the \"measurement_dates\" parameter to map into their respective dates.",
            )
        else
            if !(eltype(df[!, :measurements]) <: AbstractString)
                df.measurements = [String("$x") for x in df.measurements]
            end
            if isnothing(measurement_dates)
                # Parse df.measurements into dates
                measurements = sort(String.(unique(df.measurements)))
                df[!, "dates"] .= Dates.now()
                for m in measurements
                    # m = measurements[1]
                    validate_date(m)
                    idx = findall(df.measurements .== m)
                    length(idx) == 0 ? error("Measurement \"$m\" not found in the dataframe!") : nothing
                    df.dates[idx] .= Date(m, dateformat"yyyy-mm-dd")
                end
            else
                # Use the measurement_dates parameter to map the measurements with their respective dates
                measurements = sort(String.(unique(df.measurements)))
                measurements_input = sort(String.(keys(measurement_dates)))
                if measurements != sort(measurements ∩ measurements_input)
                    error(
                        "Please define all the dates for all the measurements. We have the following measurements: [$(join(measurements, ", "))] but only the following were defined in the input: [$(join(measurements_input, ", "))]",
                    )
                end
                df[!, "dates"] .= Dates.now()
                for (k, v) in measurement_dates
                    # k = string.(keys(measurement_dates))[1]; v = measurement_dates[k]
                    # v = "10062026"
                    # v = "2025/03/dd"
                    validate_date(v)
                    idx = findall(df.measurements .== k)
                    # println("k=$k; v=$v; length(idx)=$(length(idx))")
                    length(idx) == 0 ? error("Measurement \"$k\" not found in the dataframe!") : nothing
                    df.dates[idx] .= Date(v, dateformat"yyyy-mm-dd")
                end
            end
        end
    end
    nothing
end
