"""
    simulate_reference_genome(
        ;
        fname_reference_genome::String="simulated_reference_genome.fa",
        n_bases::Int64=10_000,
        n_chromosomes::Int64=7,
        max_characters_per_line::Int64=80,
        overwrite::Bool=true,
    )::Nothing

Generate a simulated reference genome in FASTA format.

The genome is composed of a specified number of chromosomes whose combined length
equals `n_bases`. Chromosome sequences are generated by randomly sampling the DNA
bases `A`, `T`, `C`, and `G`. Each chromosome is written as a separate FASTA record
with a header of the form `>chromN`.

Sequence lines are wrapped according to `max_characters_per_line` to produce a
standard FASTA-formatted output file.

# Arguments

- `fname_reference_genome::String="simulated_reference_genome.fa"`: Path to the
  output FASTA file.
- `n_bases::Int64=10_000`: Total number of bases to generate across all
  chromosomes.
- `n_chromosomes::Int64=7`: Number of chromosomes to simulate.
- `max_characters_per_line::Int64=80`: Maximum number of sequence characters per
  FASTA line.
- `overwrite::Bool=true`: If `true`, replace an existing output file.

# Returns

- `Nothing`: The simulated genome is written to disk.

# Throws

- `ErrorException`: If the output file already exists and `overwrite` is `false`.

# Notes

- Chromosome lengths are generated by partitioning `n_bases` into
  `n_chromosomes` intervals.
- Nucleotide bases are sampled uniformly from `['A', 'T', 'C', 'G']`.
- Existing output files are removed before writing when `overwrite=true`.
- FASTA headers are written in the format `>chrom1`, `>chrom2`, ..., `>chromN`.
- The function writes directly to disk and does not return the generated
  sequences.

# Examples

```jldoctest; setup=:(using GenomicBreedingCore, GenomicBreedingIO, GenomicBreedingDB, DataFrames, CSV, StatsBase, LibPQ, Dates)
julia> simulate_reference_genome(n_chromosomes=10);

julia> io = open("simulated_reference_genome.fa", "r");

julia> [!isnothing(match(Regex("^>"), line)) for line in eachline(io)] |> sum
10

julia> close(io);
```
"""
function simulate_reference_genome(;
    fname_reference_genome::String = "simulated_reference_genome.fa",
    n_bases::Int64 = 10_000,
    n_chromosomes::Int64 = 7,
    max_characters_per_line::Int64 = 80,
    overwrite::Bool = true,
)::Nothing
    # fname_reference_genome::String = "simulated_reference_genome.fa"; n_bases::Int64 = 1_000_000; n_chromosomes::Int64 = 7; max_characters_per_line::Int64 = 80; overwrite::Bool = true;
    if isfile(fname_reference_genome) && !overwrite
        error("The \"$fname_reference_genome\" file exists and overwrite is set to false!")
    end
    if isfile(fname_reference_genome) && overwrite
        rm(fname_reference_genome)
    end
    idx_fin = vcat(sort(sample(1:(n_bases-1), n_chromosomes-1, replace = false)), n_bases)
    idx_ini = vcat([1], idx_fin[1:(end-1)] .+ 1)
    open(fname_reference_genome, "w") do io
        # io = open(fname_reference_genome, "w")
        for i = 1:n_chromosomes
            # i = 1
            n = idx_fin[i] - (idx_ini[i]-1)
            seq = sample(['A', 'T', 'C', 'G'], n)
            counter = 0
            println(io, ">chrom$i")
            for s in seq
                # s = seq[1]
                if counter < max_characters_per_line
                    counter += 1
                    write(io, s)
                else
                    counter = 0
                    write(io, "\n$s")
                end
            end
            write(io, '\n')
        end
        # close(io)
    end
    nothing
end

"""
    simulate_genomes(
        ;
        fname_reference_genome::String="simulated_reference_genome.fa",
        fname_genomes_vcf::String="simulated_genomes.vcf",
        fname_genomes_jld2::String="simulated_genomes.jld2",
        n::Int64=100,
        l::Int64=10_000,
        n_chroms::Int64=7,
        n_alleles::Int64=2,
        max_pos::Int64=135_000_000,
        ld_corr_50perc_kb::Int64=0,
        n_populations::Int64=3,
        overwrite::Bool=true,
        verbose::Bool=false,
    )::Genomes

Simulate a population of genomes and export the results in multiple file formats.

The function generates a synthetic genomic dataset using
`GenomicBreedingCore.simulategenomes`, creates a compatible simulated reference
genome in FASTA format, and writes the simulated genomes to both VCF and JLD2
files. The generated `Genomes` object is returned for immediate use in downstream
analyses.

The reference genome size is automatically determined from the maximum genomic
position present in the simulated loci.

# Arguments

- `fname_reference_genome::String="simulated_reference_genome.fa"`: Path to the
  output reference genome FASTA file.
- `fname_genomes_vcf::String="simulated_genomes.vcf"`: Path to the output VCF file.
- `fname_genomes_jld2::String="simulated_genomes.jld2"`: Path to the output JLD2
  file.
- `n::Int64=100`: Number of individuals to simulate.
- `l::Int64=10_000`: Number of loci to simulate.
- `n_chroms::Int64=7`: Number of chromosomes.
- `n_alleles::Int64=2`: Number of alleles per locus.
- `max_pos::Int64=135_000_000`: Maximum genomic position for simulated loci.
- `ld_corr_50perc_kb::Int64=0`: Distance, in kilobases, at which linkage
  disequilibrium decays to approximately 50% correlation.
- `n_populations::Int64=3`: Number of populations to simulate.
- `overwrite::Bool=true`: If `true`, overwrite existing output files.
- `verbose::Bool=false`: If `true`, display progress and diagnostic messages during
  simulation.

# Returns

- `Genomes`: Simulated genomic dataset.

# Notes

- Genome simulation is performed using
  `GenomicBreedingCore.simulategenomes`.
- A reference genome is generated automatically using
  `simulate_reference_genome`.
- The reference genome length is determined from the largest simulated locus
  position.
- Simulated genomes are exported to both VCF and JLD2 formats for compatibility
  with downstream workflows.
- Existing output files may be replaced when `overwrite=true`.

# Examples

```jldoctest; setup=:(using GenomicBreedingCore, GenomicBreedingIO, GenomicBreedingDB, DataFrames, CSV, StatsBase, LibPQ, Dates)
julia> genomes = simulate_genomes();

julia> checkdims(genomes)
true

julia> isfile("simulated_reference_genome.fa")
true

julia> isfile("simulated_genomes.vcf")
true

julia> isfile("simulated_genomes.jld2")
true
```
"""
function simulate_genomes(;
    fname_reference_genome::String = "simulated_reference_genome.fa",
    fname_genomes_vcf::String = "simulated_genomes.vcf",
    fname_genomes_jld2::String = "simulated_genomes.jld2",
    n::Int64 = 100,
    l::Int64 = 10_000,
    n_chroms::Int64 = 7,
    n_alleles::Int64 = 2,
    max_pos::Int64 = 135_000_000,
    ld_corr_50perc_kb::Int64 = 0,
    n_populations::Int64 = 3,
    overwrite::Bool = true,
    verbose::Bool = false,
)::Genomes
    # fname_reference_genome::String = "simulated_reference_genome.fa"; fname_genomes_vcf::String = "simulated_genomes.vcf"; fname_genomes_jld2::String = "simulated_genomes.jld2";
    # n::Int64 = 100; l::Int64 = 10_000; n_chroms::Int64 = 7; n_alleles::Int64 = 2; max_pos::Int64 = 135_000_000; ld_corr_50perc_kb::Int64 = 0; n_populations::Int64 = 3; overwrite::Bool = true; verbose::Bool = false
    genomes = GenomicBreedingCore.simulategenomes(
        n = n,
        l = l,
        n_chroms = n_chroms,
        n_alleles = n_alleles,
        max_pos = max_pos,
        ld_corr_50perc_kb = ld_corr_50perc_kb,
        n_populations = n_populations,
        verbose = verbose,
    )
    simulate_reference_genome(
        fname_reference_genome = fname_reference_genome,
        n_bases = maximum([parse(Int64, x[2]) for x in split.(genomes.loci_alleles, "\t")]),
        n_chromosomes = n_chroms,
        max_characters_per_line = 80,
        overwrite = overwrite,
    )
    GenomicBreedingIO.writevcf(genomes, fname = fname_genomes_vcf, overwrite = overwrite)
    GenomicBreedingIO.writejld2(genomes, fname = fname_genomes_jld2, overwrite = overwrite)
    genomes
end

"""
    simulate_trials(
        genomes::Genomes;
        fname_trials_tsv::String="simulated_trials.tsv",
        n_years::Int64=2,
        n_seasons::Int64=4,
        n_measurements::Int64=2,
        n_sites::Int64=2,
        n_replications::Int64=2,
        sparsity::Float64=0.05,
        overwrite::Bool=true,
        verbose::Bool=false,
    )::Trials

Simulate multi-environment trial data from a genomic dataset and export the results
to a tab-delimited file.

The function generates synthetic trial data using a supplied `Genomes` object and a
set of experimental design parameters. Simulated trials are written to disk as a TSV
file and returned as a `Trials` object for immediate downstream use.

Prior to simulation, the function verifies that the genomic data are valid and that
existing output files may be overwritten according to the specified settings.

# Arguments

- `genomes::Genomes`: Genomic dataset used as the basis for trial simulation.
- `fname_trials_tsv::String="simulated_trials.tsv"`: Path to the output TSV file.
- `n_years::Int64=2`: Number of years to simulate.
- `n_seasons::Int64=4`: Number of seasons per year.
- `n_measurements::Int64=2`: Number of measurement events.
- `n_sites::Int64=2`: Number of trial sites.
- `n_replications::Int64=2`: Number of replications per trial.
- `sparsity::Float64=0.05`: Proportion of missing observations to introduce into
  the simulated dataset.
- `overwrite::Bool=true`: If `true`, overwrite existing output files.
- `verbose::Bool=false`: If `true`, display progress and diagnostic messages during
  simulation.

# Returns

- `Trials`: Simulated trial dataset.

# Throws

- `ErrorException`: If the supplied `Genomes` object fails validation.
- `ErrorException`: If the output file already exists and `overwrite` is `false`.

# Notes

- Input genomic data are validated using `checkdims` before simulation.
- Trial simulation is performed using
  `GenomicBreedingCore.simulatetrials`.
- Simulated trials are exported using
  `GenomicBreedingIO.writedelimited`.
- Existing output files are removed before writing when `overwrite=true`.
- The returned `Trials` object is the same dataset written to disk.

# Examples

```jldoctest; setup=:(using GenomicBreedingCore, GenomicBreedingIO, GenomicBreedingDB, DataFrames, CSV, StatsBase, LibPQ, Dates)
julia> trials = simulate_genomes() |> simulate_trials;

julia> checkdims(trials)
true

julia> isfile("simulated_trials.tsv")
true
```
"""
function simulate_trials(
    genomes::Genomes;
    fname_trials_tsv::String = "simulated_trials.tsv",
    n_years::Int64 = 2,
    n_seasons::Int64 = 4,
    n_measurements::Int64 = 2,
    n_sites::Int64 = 2,
    n_replications::Int64 = 2,
    sparsity::Float64 = 0.05,
    overwrite::Bool = true,
    verbose::Bool = false,
)::Trials
    # genomes = simulate_genomes(); genomes = genomes; fname_trials_tsv::String = "simulated_trials.tsv";
    # n_years::Int64 = 2; n_seasons::Int64 = 4; n_measurements::Int64 = 2; n_sites::Int64 = 2; n_replications::Int64 = 2; sparsity::Float64 = 0.05; overwrite::Bool = true; verbose::Bool = false
    if !checkdims(genomes)
        error("Genomes struct is corrupted!")
    end
    if isfile(fname_trials_tsv) && !overwrite
        error("The \"$fname_trials_tsv\" file exists and overwrite is set to false!")
    end
    if isfile(fname_trials_tsv) && overwrite
        rm(fname_trials_tsv)
    end
    trials, _ = GenomicBreedingCore.simulatetrials(
        genomes = genomes,
        n_years = n_years,
        n_seasons = n_seasons,
        n_measurements = n_measurements,
        n_sites = n_sites,
        n_replications = n_replications,
        sparsity = sparsity,
        verbose = verbose,
    )
    GenomicBreedingIO.writedelimited(trials, fname = fname_trials_tsv, overwrite = overwrite)
    trials
end

"""
    simulate_environments(
        trials::Trials;
        fname_environments_tsv::String="simulated_environments.tsv",
        n_measurements_in_between_phenotypings::Int64=10,
        sparsity::Float64=0.05,
        overwrite::Bool=true,
        verbose::Bool=false,
    )::DataFrame

Simulate environmental measurements associated with a trial dataset and export the
results to a tab-delimited file.

The function generates synthetic environmental observations for combinations of
measurement dates and trial identifiers. Additional measurement dates are inserted
between phenotyping events to create a more densely sampled environmental time
series. Environmental variables such as rainfall, temperature, humidity, and solar
radiation are then simulated and optionally populated with missing values according
to the specified sparsity level.

The resulting environmental dataset is written to disk and returned as a
`DataFrame`.

# Arguments

- `trials::Trials`: Trial dataset used to define the experimental structure and
  measurement schedule.
- `fname_environments_tsv::String="simulated_environments.tsv"`: Path to the output
  TSV file.
- `n_measurements_in_between_phenotypings::Int64=10`: Number of environmental
  measurement dates to generate between consecutive phenotyping dates.
- `sparsity::Float64=0.05`: Proportion of environmental observations to replace
  with `missing`.
- `overwrite::Bool=true`: If `true`, overwrite an existing output file.
- `verbose::Bool=false`: If `true`, display progress information during
  simulation.

# Returns

- `DataFrame`: Simulated environmental dataset.

# Throws

- `ErrorException`: If the output file already exists and `overwrite` is `false`.
- `ErrorException`: If the trial data do not contain a `measurements` column.
- `ErrorException`: If trial measurement dates cannot be validated.

# Notes

- Trial data are first converted to a tabular representation using `tabularise`.
- Environmental records are generated for unique combinations of measurements,
  sites, experiments, and treatments when present.
- Intermediate measurement dates are interpolated between phenotyping events.
- Simulated environmental variables include rainfall, solar radiation, minimum
  temperature, maximum temperature, and humidity.
- Missing values are introduced randomly according to the specified `sparsity`
  level.
- Results are written as a tab-delimited file using `CSV.write`.
- Existing output files are removed before writing when `overwrite=true`.

# Examples

```jldoctest; setup=:(using GenomicBreedingCore, GenomicBreedingIO, GenomicBreedingDB, DataFrames, CSV, StatsBase, LibPQ, Dates)
julia> df_environments = simulate_genomes() |> simulate_trials |> simulate_environments;

julia> prod(size(df_environments)) > 0
true

julia> isfile("simulated_environments.tsv")
true
```
"""
function simulate_environments(
    trials::Trials;
    fname_environments_tsv::String = "simulated_environments.tsv",
    n_measurements_in_between_phenotypings::Int64 = 10,
    sparsity::Float64 = 0.05,
    overwrite::Bool = true,
    verbose::Bool = false,
)::DataFrame
    # genomes = simulate_genomes(); trials = simulate_trials(genomes); trials = trials
    # fname_environments_tsv::String = "simulated_environments.tsv"; overwrite::Bool = true; verbose::Bool = false; n_measurements_in_between_phenotypings::Int64 = 10; sparsity=0.05
    if isfile(fname_environments_tsv) && !overwrite
        error("The \"$fname_environments_tsv\" file exists and overwrite is set to false!")
    end
    if isfile(fname_environments_tsv) && overwrite
        rm(fname_environments_tsv)
    end
    df_trial = tabularise(trials)
    validate_trials(df_trial)
    if "measurements"∉names(df_trial)
        error("Missing required measurement dates!")
    end
    measurements = sort([String("$x") for x in unique(df_trial.measurements)])
    validate_date.(measurements)
    # Define multiple measurement days
    measurement_dates = String[]
    if length(measurements) == 1
        for x in measurements
            # x = measurements[1]
            d = Date(x, dateformat"yyyy-mm-dd")
            append!(
                measurement_dates,
                [String("$x") for x in collect(d:Day(1):(d+Day(n_measurements_in_between_phenotypings)))],
            )
        end
    else
        for i = 2:length(measurements)
            # i = 2
            d_ini = Date(measurements[i-1], dateformat"yyyy-mm-dd")
            d_fin = Date(measurements[i], dateformat"yyyy-mm-dd")
            d_step = Day(ceil((d_fin - d_ini) / Day(n_measurements_in_between_phenotypings)))
            append!(measurement_dates, [String("$x") for x in collect(d_ini:d_step:d_fin)])
        end
    end
    measurement_dates = unique(measurement_dates)
    # Find all unique combinatons of the id columns except measurements from the input trial dataframe
    existing_id_columns = names(df_trial) ∩ ["sites", "experiments", "treatments"] # except measurements
    ids_concat_tmp = String[]
    for id in existing_id_columns
        # id = existing_id_columns[1]
        ids_concat_tmp = if length(ids_concat_tmp) == 0
            String.(df_trial[!, id])
        else
            String.(string.(ids_concat_tmp, "|||", df_trial[!, id]))
        end
    end
    ids_concat_tmp = unique(ids_concat_tmp)
    # Include the measurement dates
    ids_concat = String[]
    for m in measurement_dates
        # m = measurement_dates[1]
        append!(ids_concat, string.(m, "|||", ids_concat_tmp))
    end
    ids_concat = unique(ids_concat)
    ids_concat_split = split.(ids_concat, "|||")
    existing_id_columns = vcat(["measurements"], existing_id_columns)
    # Instantiate the output dataframe using the unique id combinations
    df_environments = DataFrame()
    for j = 1:length(existing_id_columns)
        # j = 1
        df_environments[!, existing_id_columns[j]] = [String(x[j]) for x in ids_concat_split]
    end
    # Simulate roughly environment data
    environment_variables = Dict(
        "rainfall_mm_per_day" => collect(0.0:123.0),
        "solar_radiation_MJ_per_m2_per_day" => collect(3.0:28.0),
        "minimum_temperature_C_per_day" => collect(-2.0:32.0),
        "maximum_temperature_C_per_day" => collect(6.0:47.0),
        "humidity_perc_per_day" => collect(15.0:100.0),
    )
    n_missing = Int64(round(sparsity * nrow(df_environments)))
    pb = ProgressMeter.Progress(length(environment_variables), "Simulation environmental data...")
    for (k, v) in environment_variables
        # k = "rainfall_mm_per_day"; v = environment_variables[k]
        y::Vector{Union{Missing,Float64}} = rand(v, nrow(df_environments))
        y = if n_missing == 0
            y
        else
            idx_missing = rand(1:nrow(df_environments), n_missing)
            y[idx_missing] .= missing
            y
        end
        df_environments[!, k] = y
        if verbose
            ProgressMeter.next!(pb)
        end
    end
    if verbose
        ProgressMeter.finish!(pb)
    end
    CSV.write(fname_environments_tsv, df_environments; delim = '\t')
    df_environments
end

"""
    simulate_phenomes(
        trials::Trials;
        fname_phenomes_jld2::String="simulated_phenomes.jld2",
        overwrite::Bool=true,
    )::Phenomes

Generate a phenomic dataset from a trial dataset and export the result as a JLD2
file.

The function extracts phenomic information from the supplied `Trials` object using
`extractphenomes`, writes the resulting `Phenomes` object to disk, and returns it
for immediate downstream use.

Existing output files may be overwritten according to the value of `overwrite`.

# Arguments

- `trials::Trials`: Trial dataset from which phenomic data will be extracted.
- `fname_phenomes_jld2::String="simulated_phenomes.jld2"`: Path to the output JLD2
  file.
- `overwrite::Bool=true`: If `true`, overwrite an existing output file.

# Returns

- `Phenomes`: Extracted phenomic dataset.

# Throws

- `ErrorException`: If the output file already exists and `overwrite` is `false`.

# Notes

- Phenomic data are generated using `extractphenomes`.
- The resulting dataset is exported using `GenomicBreedingIO.writejld2`.
- Existing output files are removed before writing when `overwrite=true`.
- The returned `Phenomes` object is the same dataset written to disk.

# Examples

```jldoctest; setup=:(using GenomicBreedingCore, GenomicBreedingIO, GenomicBreedingDB, DataFrames, CSV, StatsBase, LibPQ, Dates)
julia> phenomes = simulate_genomes() |>  simulate_trials |> simulate_phenomes;

julia> checkdims(phenomes)
true

julia> isfile("simulated_phenomes.jld2")
true
```
"""
function simulate_phenomes(
    trials::Trials;
    fname_phenomes_jld2::String = "simulated_phenomes.jld2",
    overwrite = true,
)::Phenomes
    # genomes = simulate_genomes(); trials = simulate_trials(genomes); trials = trials
    # fname_phenomes_jld2::String = "simulated_phenomes.jld2"; overwrite=true
    if isfile(fname_phenomes_jld2) && !overwrite
        error("The \"$fname_phenomes_jld2\" file exists and overwrite is set to false!")
    end
    if isfile(fname_phenomes_jld2) && overwrite
        rm(fname_phenomes_jld2)
    end
    phenomes = extractphenomes(trials)
    # tabularise(phenomes)
    GenomicBreedingIO.writejld2(phenomes, fname = fname_phenomes_jld2, overwrite = overwrite)
    phenomes
end

"""
    simulate_fit(
        genomes::Genomes,
        phenomes::Phenomes;
        fname_fit_jld2::String="simulated_fit.jld2",
        overwrite::Bool=true,
    )::Fit

Generate a simulated genomic prediction model from compatible genomic and phenomic
datasets and export the result as a JLD2 file.

The function constructs a synthetic `Fit` object using genotype and phenotype
information from the supplied `Genomes` and `Phenomes` objects. Marker effects are
generated randomly, predictions are calculated from allele frequencies, and summary
performance metrics are computed from the observed and predicted phenotypic values.

The resulting model is written to disk and returned for subsequent analysis or
testing.

# Arguments

- `genomes::Genomes`: Genomic dataset containing marker information and allele
  frequencies.
- `phenomes::Phenomes`: Phenomic dataset containing trait measurements for the same
  set of entries.
- `fname_fit_jld2::String="simulated_fit.jld2"`: Path to the output JLD2 file.
- `overwrite::Bool=true`: If `true`, overwrite an existing output file.

# Returns

- `Fit`: Simulated genomic prediction model.

# Throws

- `ErrorException`: If the entries in `Genomes` and `Phenomes` do not align
  exactly.

# Notes

- Genomic and phenomic datasets must contain the same entries in the same order.
- Missing allele frequencies and phenotype values are replaced with `0.0` prior to
  model construction.
- The simulated model is labelled as `"OLS"`.
- Marker effects are generated randomly and are not estimated from the data.
- Predicted values are calculated as the matrix product of allele frequencies and
  simulated marker effects.
- Model performance metrics include correlation (`cor`), root mean squared error
  (`rmse`), and coefficient of determination (`r2`).
- The resulting fit is exported using `GenomicBreedingIO.writejld2`.

# Examples

```jldoctest; setup=:(using GenomicBreedingCore, GenomicBreedingIO, GenomicBreedingDB, DataFrames, CSV, StatsBase, LibPQ, Dates)
julia> genomes = simulate_genomes();

julia> phenomes = simulate_trials(genomes) |> simulate_phenomes;

julia> fit = simulate_fit(genomes, phenomes);

julia> checkdims(fit)
true

julia> isfile("simulated_fit.jld2")
true
```
"""
function simulate_fit(
    genomes::Genomes,
    phenomes::Phenomes;
    fname_fit_jld2::String = "simulated_fit.jld2",
    overwrite::Bool = true,
)::Fit
    # genomes = simulate_genomes(); trials = simulate_trials(genomes); phenomes = simulate_phenomes(trials); fname_fit_jld2::String = "simulated_fit.jld2"; overwrite = true; genomes = genomes; phenomes = sim_phenomes["phenomes"]
    if genomes.entries != phenomes.entries
        error("The Genomes and Phenomes are not compatible, i.e. the entries do not align perfectly!")
    end
    X = genomes.allele_frequencies
    X[ismissing.(X)] .= 0.0
    y = phenomes.phenotypes[:, 1]
    y[ismissing.(y)] .= 0.0
    fit = Fit(n = length(genomes.entries), l = length(genomes.loci_alleles))
    fit.model = "OLS"
    fit.b_hat_labels = genomes.loci_alleles
    fit.b_hat = rand(length(genomes.loci_alleles))
    fit.trait = phenomes.traits[1]
    fit.entries = phenomes.entries
    fit.populations = phenomes.populations
    fit.y_true = y
    fit.y_pred = X * fit.b_hat
    fit.metrics = Dict(
        "cor" => cor(fit.y_true, fit.y_pred),
        "rmse" => mean(sqrt.((fit.y_true - fit.y_pred) .^ 2)),
        "r2" => 1.00 - (var(fit.y_true - fit.y_pred) / var(fit.y_true)),
    )
    GenomicBreedingIO.writejld2(fit, fname = fname_fit_jld2, overwrite = overwrite)
    fit
end
