"""
    simulate_reference_genome(;
        fname_output::String="simulated_reference_genome.fa",
        n_bases::Int64=10_000,
        n_chromosomes::Int64=7,
        max_characters_per_line::Int64=80,
        overwrite::Bool=true,
    )::String

Simulate a reference genome and write it to a FASTA file.

The simulated genome consists of `n_chromosomes` chromosomes whose
combined length equals `n_bases`. Nucleotide sequences are generated by
randomly sampling from the bases `A`, `T`, `C`, and `G`. Chromosome
boundaries are assigned randomly while ensuring that the total genome
length matches the requested number of bases.

Sequences are written in FASTA format, with chromosome names of the form
`chrom1`, `chrom2`, ..., `chromN`.

# Arguments

- `fname_output::String="simulated_reference_genome.fa"`:
  Output FASTA file.
- `n_bases::Int64=10_000`:
  Total number of bases across all chromosomes.
- `n_chromosomes::Int64=7`:
  Number of chromosomes to simulate.
- `max_characters_per_line::Int64=80`:
  Maximum number of sequence characters written per FASTA line.
- `overwrite::Bool=true`:
  If `true`, overwrite an existing output file.

# Returns

- nothing if it saves the simulated reference genome fasta file

# Throws

- An exception if `fname_output` already exists and
  `overwrite=false`.

# FASTA Structure

The output file contains one FASTA record per chromosome:

```text
>chrom1
CAGCCGTAGAGTGAACCCCTCGGAAACTCCCTTAGCTGGTACTGCGCTTGCTCGTGCTTAGAGATAGATACCGATCTCCTA
AGTGCGACCAGGTAGACCTTCGATGTGCGTCTTCCTCGCGAATATTCCGAGGGTCAGTCGCCCATACCCATTGACTCATTG
...
>chrom2
TCACAAACATCTACCTTTCAGAATCCAGTATAGGCCGAGATAAGCTAACTTAGATATGCACAGGGTAGTACAGGTTCTATT
GCAGGTTGACATGGTCGTACAGTCACGCAAAGCTTTGGGTTCATCAGGTGCAATTTTCTACTGAGTGTGGGAGTGTGCAAC
...
```

Each sequence is wrapped so that no line exceeds max_characters_per_line characters.

# Notes
Chromosome lengths are determined randomly.
The total number of generated bases equals n_bases.
Bases are sampled uniformly from A, T, C, and G.
Intended primarily for testing, demonstration, and benchmarking workflows that require a reference genome.

# Examples

```jldoctest; setup=:(using GenomicBreedingCore, GenomicBreedingIO, GenomicBreedingDB, DataFrames, CSV, StatsBase, LibPQ, Dates)
julia> simulate_reference_genome(n_chromosomes=10);

julia> io = open("simulated_reference_genome.fa", "r");

julia> [!isnothing(match(Regex("^>"), line)) for line in eachline(io)] |> sum
10

julia> close(io);
```
"""
function simulate_reference_genome(;
    fname_reference_genome::String = "simulated_reference_genome.fa",
    n_bases::Int64 = 10_000,
    n_chromosomes::Int64 = 7,
    max_characters_per_line::Int64 = 80,
    overwrite::Bool = true,
)::Nothing
    # fname_reference_genome::String = "simulated_reference_genome.fa"; n_bases::Int64 = 1_000_000; n_chromosomes::Int64 = 7; max_characters_per_line::Int64 = 80; overwrite::Bool = true;
    if isfile(fname_reference_genome) && !overwrite
        error("The \"$fname_reference_genome\" file exists and overwrite is set to false!")
    end
    if isfile(fname_reference_genome) && overwrite
        rm(fname_reference_genome)
    end
    idx_fin = vcat(sort(sample(1:(n_bases-1), n_chromosomes-1, replace = false)), n_bases)
    idx_ini = vcat([1], idx_fin[1:(end-1)] .+ 1)
    open(fname_reference_genome, "w") do io
        # io = open(fname_reference_genome, "w")
        for i = 1:n_chromosomes
            # i = 1
            n = idx_fin[i] - (idx_ini[i]-1)
            seq = sample(['A', 'T', 'C', 'G'], n)
            counter = 0
            println(io, ">chrom$i")
            for s in seq
                # s = seq[1]
                if counter < max_characters_per_line
                    counter += 1
                    write(io, s)
                else
                    counter = 0
                    write(io, "\n$s")
                end
            end
            write(io, '\n')
        end
        # close(io)
    end
    nothing
end

"""
	simulate_genomes(;
		fname_reference_genome::String = "simulated_reference_genome.fa",
		fname_genomes_vcf::String = "simulated_genomes.vcf",
		fname_genomes_jld2::String = "simulated_genomes.jld2",
		n::Int64 = 100,
		l::Int64 = 10_000,
		n_chroms::Int64 = 7,
		n_alleles::Int64 = 2,
		max_pos::Int64 = 135_000_000,
		ld_corr_50perc_kb::Int64 = 0,
		n_populations::Int64 = 3,
		overwrite::Bool = true,
		verbose::Bool = false,
	)::Genomes

Simulate a set of genomes and export the results in multiple common genomic
data formats.

This function generates a synthetic population using
`GenomicBreedingCore.simulategenomes`, creates a compatible reference genome
FASTA file, and writes the simulated genomic data to both VCF and JLD2 formats.

# Keyword Arguments

## Output files

- `fname_reference_genome::String="simulated_reference_genome.fa"`:
  Output FASTA file containing the simulated reference genome.
- `fname_genomes_vcf::String="simulated_genomes.vcf"`:
  Output VCF file containing the simulated variants.
- `fname_genomes_jld2::String="simulated_genomes.jld2"`:
  Output JLD2 file containing the simulated `Genomes` object.

## Genome simulation

- `n::Int64=100`:
  Number of individuals to simulate.
- `l::Int64=10_000`:
  Number of loci to simulate.
- `n_chroms::Int64=7`:
  Number of chromosomes.
- `n_alleles::Int64=2`:
  Number of alleles per locus.
- `max_pos::Int64=135_000_000`:
  Maximum genomic position within each chromosome.
- `ld_corr_50perc_kb::Int64=0`:
  Distance (kb) at which linkage disequilibrium decays to approximately
  50%. A value of `0` disables distance-based LD simulation.
- `n_populations::Int64=3`:
  Number of populations represented in the simulated genomes.

## Miscellaneous

- `overwrite::Bool=true`:
  Overwrite existing output files.
- `verbose::Bool=false`:
  Print progress and diagnostic information.

# Returns

- `"genomes"`:
  The simulated `Genomes` object.

# Examples

```jldoctest; setup=:(using GenomicBreedingCore, GenomicBreedingIO, GenomicBreedingDB, DataFrames, CSV, StatsBase, LibPQ, Dates)
julia> genomes = simulate_genomes();

julia> checkdims(genomes)
true

julia> isfile("simulated_reference_genome.fa")
true

julia> isfile("simulated_genomes.vcf")
true

julia> isfile("simulated_genomes.jld2")
true
```
"""
function simulate_genomes(;
    fname_reference_genome::String = "simulated_reference_genome.fa",
    fname_genomes_vcf::String = "simulated_genomes.vcf",
    fname_genomes_jld2::String = "simulated_genomes.jld2",
    n::Int64 = 100,
    l::Int64 = 10_000,
    n_chroms::Int64 = 7,
    n_alleles::Int64 = 2,
    max_pos::Int64 = 135_000_000,
    ld_corr_50perc_kb::Int64 = 0,
    n_populations::Int64 = 3,
    overwrite::Bool = true,
    verbose::Bool = false,
)::Genomes
    # fname_reference_genome::String = "simulated_reference_genome.fa"; fname_genomes_vcf::String = "simulated_genomes.vcf"; fname_genomes_jld2::String = "simulated_genomes.jld2";
    # n::Int64 = 100; l::Int64 = 10_000; n_chroms::Int64 = 7; n_alleles::Int64 = 2; max_pos::Int64 = 135_000_000; ld_corr_50perc_kb::Int64 = 0; n_populations::Int64 = 3; overwrite::Bool = true; verbose::Bool = false
    genomes = GenomicBreedingCore.simulategenomes(
        n = n,
        l = l,
        n_chroms = n_chroms,
        n_alleles = n_alleles,
        max_pos = max_pos,
        ld_corr_50perc_kb = ld_corr_50perc_kb,
        n_populations = n_populations,
        verbose = verbose,
    )
    simulate_reference_genome(
        fname_reference_genome = fname_reference_genome,
        n_bases = maximum([parse(Int64, x[2]) for x in split.(genomes.loci_alleles, "\t")]),
        n_chromosomes = n_chroms,
        max_characters_per_line = 80,
        overwrite = overwrite,
    )
    GenomicBreedingIO.writevcf(genomes, fname = fname_genomes_vcf, overwrite = overwrite)
    GenomicBreedingIO.writejld2(genomes, fname = fname_genomes_jld2, overwrite = overwrite)
    genomes
end

"""
	simulate_trials(
		genomes::Genomes;
		fname_trials_tsv::String = "simulated_trials.tsv",
		n_years::Int64 = 2,
		n_seasons::Int64 = 4,
		n_measurements::Int64 = 2,
		n_sites::Int64 = 2,
		n_replications::Int64 = 2,
		sparsity::Float64 = 0.05,
		overwrite::Bool = true,
		verbose::Bool = false,
	)::Trials

Simulate multi-environment trial data from a set of genomes and export the
resulting observations to a tab-delimited file.

This function generates phenotypic observations using
`GenomicBreedingCore.simulatetrials`, optionally introducing missing values,
and writes the resulting `Trials` object to disk. The supplied `Genomes`
object is validated before simulation begins.

# Arguments

- `genomes::Genomes`:
  A valid `Genomes` object describing the individuals and genetic markers
  from which trial observations will be simulated.

# Keyword Arguments

## Output files

- `fname_trials_tsv::String="simulated_trials.tsv"`:
  Output tab-delimited file containing the simulated trial data.

## Trial design

- `n_years::Int64=2`:
  Number of years in the simulated trial program.
- `n_seasons::Int64=4`:
  Number of seasons per year.
- `n_measurements::Int64=2`:
  Number of measurements collected per experimental unit.
- `n_sites::Int64=2`:
  Number of trial locations.
- `n_replications::Int64=2`:
  Number of replications per site.

## Data properties

- `sparsity::Float64=0.05`:
  Proportion of observations that are randomly set to missing.

## Miscellaneous

- `overwrite::Bool=true`:
  Overwrite the output file if it already exists.
- `verbose::Bool=false`:
  Print progress and diagnostic messages during simulation.

# Returns

- `"trials"`:
  The simulated `Trials` object.

  # Throws

- `ErrorException` if `checkdims(genomes)` returns `false`, indicating that
  the supplied `Genomes` object is invalid or corrupted.

# Examples

```jldoctest; setup=:(using GenomicBreedingCore, GenomicBreedingIO, GenomicBreedingDB, DataFrames, CSV, StatsBase, LibPQ, Dates)
julia> trials = simulate_genomes() |> simulate_trials;

julia> checkdims(trials)
true

julia> isfile("simulated_trials.tsv")
true
```
"""
function simulate_trials(
    genomes::Genomes;
    fname_trials_tsv::String = "simulated_trials.tsv",
    n_years::Int64 = 2,
    n_seasons::Int64 = 4,
    n_measurements::Int64 = 2,
    n_sites::Int64 = 2,
    n_replications::Int64 = 2,
    sparsity::Float64 = 0.05,
    overwrite::Bool = true,
    verbose::Bool = false,
)::Trials
    # genomes = simulate_genomes(); genomes = genomes; fname_trials_tsv::String = "simulated_trials.tsv";
    # n_years::Int64 = 2; n_seasons::Int64 = 4; n_measurements::Int64 = 2; n_sites::Int64 = 2; n_replications::Int64 = 2; sparsity::Float64 = 0.05; overwrite::Bool = true; verbose::Bool = false
    if !checkdims(genomes)
        error("Genomes struct is corrupted!")
    end
    if isfile(fname_trials_tsv) && !overwrite
        error("The \"$fname_trials_tsv\" file exists and overwrite is set to false!")
    end
    if isfile(fname_trials_tsv) && overwrite
        rm(fname_trials_tsv)
    end
    trials, _ = GenomicBreedingCore.simulatetrials(
        genomes = genomes,
        n_years = n_years,
        n_seasons = n_seasons,
        n_measurements = n_measurements,
        n_sites = n_sites,
        n_replications = n_replications,
        sparsity = sparsity,
        verbose = verbose,
    )
    GenomicBreedingIO.writedelimited(trials, fname = fname_trials_tsv, overwrite = overwrite)
    trials
end


"""
    simulate_environments(
        trials::Trials;
        fname_output::String="simulated_environments.tsv",
        n_measurements_in_between_phenotypings::Int64=10,
        sparsity::Float64=0.05,
        overwrite::Bool=true,
        verbose::Bool=false,
    )::DataFrame

Simulate environmental measurements for a trial dataset.

This function generates synthetic environmental covariates from a `Trials`
object. The trial observations are first converted to a tabular
representation and validated. Unique phenotyping dates are extracted from the
`measurements` column and environmental measurement dates are generated either:

- Daily for a specified duration when only a single phenotyping date exists.
- At approximately regular intervals between consecutive phenotyping dates
  when multiple phenotyping dates exist.

Environmental measurements are then simulated for each unique combination of
measurement date and trial identifiers (`sites`, `experiments`, and
`treatments`, when present).

The following environmental variables are generated:

- `rainfall_mm_per_day`
- `solar_radiation_MJ_per_m2_per_day`
- `minimum_temperature_C_per_day`
- `maximum_temperature_C_per_day`
- `humidity_perc_per_day`

Values are sampled independently from predefined ranges and are intended for
testing, examples, tutorials, and workflow development.

# Arguments

- `trials::Trials`:
  A valid `Trials` object containing a `measurements` field with one or more
  phenotyping dates.

# Keyword Arguments

- `fname_output::String="simulated_environments.tsv"`:
  Output tab-delimited file containing the simulated environmental data.
- `n_measurements_in_between_phenotypings::Int64=10`:
  Number of environmental measurement intervals generated between consecutive
  phenotyping dates. If only a single phenotyping date is present,
  measurements are generated daily for this many days following that date.
- `sparsity::Float64=0.05`:
  Proportion of simulated environmental observations to replace with
  `missing`.
- `overwrite::Bool=true`:
  Overwrite an existing output file.
- `verbose::Bool=false`:
  Display progress information during simulation.

# Returns
- `"df_environments"`:
  DataFrame containing the simulated environmental data.

# Throws

- `ErrorException` if the trial dataset is invalid.
- `ErrorException` if the required `measurements` column is absent.

# Notes

- Environmental variables are simulated independently and therefore do not
  exhibit realistic meteorological correlations.
- Generated values should not be used for scientific inference.
- The output is intended primarily for software testing, demonstrations, and
  benchmarking workflows.

# Example

```jldoctest; setup=:(using GenomicBreedingCore, GenomicBreedingIO, GenomicBreedingDB, DataFrames, CSV, StatsBase, LibPQ, Dates)
julia> df_environments = simulate_genomes() |> simulate_trials |> simulate_environments;

julia> prod(size(df_environments)) > 0
true

julia> isfile("simulated_environments.tsv")
true
```
"""
function simulate_environments(
    trials::Trials;
    fname_environments::String = "simulated_environments.tsv",
    n_measurements_in_between_phenotypings::Int64 = 10,
    sparsity::Float64 = 0.05,
    overwrite::Bool = true,
    verbose::Bool = false,
)::DataFrame
    # genomes = simulate_genomes(); trials = simulate_trials(genomes); trials = trials
    # fname_environments::String = "simulated_environments.tsv"; overwrite::Bool = true; verbose::Bool = false; n_measurements_in_between_phenotypings::Int64 = 10; sparsity=0.05
    if isfile(fname_environments) && !overwrite
        error("The \"$fname_environments\" file exists and overwrite is set to false!")
    end
    if isfile(fname_environments) && overwrite
        rm(fname_environments)
    end
    df_trial = tabularise(trials)
    validate_trials(df_trial)
    if "measurements"∉names(df_trial)
        error("Missing required measurement dates!")
    end
    measurements = sort([String("$x") for x in unique(df_trial.measurements)])
    validate_date.(measurements)
    # Define multiple measurement days
    measurement_dates = String[]
    if length(measurements) == 1
        for x in measurements
            # x = measurements[1]
            d = Date(x, dateformat"yyyy-mm-dd")
            append!(
                measurement_dates,
                [String("$x") for x in collect(d:Day(1):(d+Day(n_measurements_in_between_phenotypings)))],
            )
        end
    else
        for i = 2:length(measurements)
            # i = 2
            d_ini = Date(measurements[i-1], dateformat"yyyy-mm-dd")
            d_fin = Date(measurements[i], dateformat"yyyy-mm-dd")
            d_step = Day(ceil((d_fin - d_ini) / Day(n_measurements_in_between_phenotypings)))
            append!(measurement_dates, [String("$x") for x in collect(d_ini:d_step:d_fin)])
        end
    end
    measurement_dates = unique(measurement_dates)
    # Find all unique combinatons of the id columns except measurements from the input trial dataframe
    existing_id_columns = names(df_trial) ∩ ["sites", "experiments", "treatments"] # except measurements
    ids_concat_tmp = String[]
    for id in existing_id_columns
        # id = existing_id_columns[1]
        ids_concat_tmp = if length(ids_concat_tmp) == 0
            String.(df_trial[!, id])
        else
            String.(string.(ids_concat_tmp, "|||", df_trial[!, id]))
        end
    end
    ids_concat_tmp = unique(ids_concat_tmp)
    # Include the measurement dates
    ids_concat = String[]
    for m in measurement_dates
        # m = measurement_dates[1]
        append!(ids_concat, string.(m, "|||", ids_concat_tmp))
    end
    ids_concat = unique(ids_concat)
    ids_concat_split = split.(ids_concat, "|||")
    existing_id_columns = vcat(["measurements"], existing_id_columns)
    # Instantiate the output dataframe using the unique id combinations
    df_environments = DataFrame()
    for j = 1:length(existing_id_columns)
        # j = 1
        df_environments[!, existing_id_columns[j]] = [String(x[j]) for x in ids_concat_split]
    end
    # Simulate roughly environment data
    environment_variables = Dict(
        "rainfall_mm_per_day" => collect(0.0:123.0),
        "solar_radiation_MJ_per_m2_per_day" => collect(3.0:28.0),
        "minimum_temperature_C_per_day" => collect(-2.0:32.0),
        "maximum_temperature_C_per_day" => collect(6.0:47.0),
        "humidity_perc_per_day" => collect(15.0:100.0),
    )
    n_missing = Int64(round(sparsity * nrow(df_environments)))
    pb = ProgressMeter.Progress(length(environment_variables), "Simulation environmental data...")
    for (k, v) in environment_variables
        # k = "rainfall_mm_per_day"; v = environment_variables[k]
        y::Vector{Union{Missing,Float64}} = rand(v, nrow(df_environments))
        y = if n_missing == 0
            y
        else
            idx_missing = rand(1:nrow(df_environments), n_missing)
            y[idx_missing] .= missing
            y
        end
        df_environments[!, k] = y
        if verbose
            ProgressMeter.next!(pb)
        end
    end
    if verbose
        ProgressMeter.finish!(pb)
    end
    CSV.write(fname_environments, df_environments; delim = '\t')
    df_environments
end

"""
    simulate_phenomes(
        trials::Trials;
        fname_phenomes::String = "simulated_phenomes.jld2",
        overwrite=true,
    )::Phenomes

Extract phenomic observations from a `Trials` object and save them as a JLD2
file.

This function derives a `Phenomes` object from the supplied trial data using
`extractphenomes` and writes the resulting object to disk. Existing output
files may optionally be overwritten.

# Arguments

- `trials::Trials`:
  A valid `Trials` object containing phenotypic observations and associated
  experimental metadata.

# Keyword Arguments

- `fname_phenomes::String="simulated_phenomes.jld2"`:
  Output JLD2 filename for the extracted phenomic data.
- `overwrite::Bool=true`:
  Overwrite an existing output file if present.

# Returns
- `"phenomes"`:
  The simulated `Phenomes` object.

# Throws

- `ErrorException` if the output file already exists and
  `overwrite=false`.

# Notes

- Phenomes are extracted directly from the supplied trial dataset using
  `extractphenomes`.
- The resulting file can be reloaded using
  `GenomicBreedingIO.readjld2`.
- This function provides a convenient bridge between simulated trial data
  and downstream phenomic analyses.

# Example

```jldoctest; setup=:(using GenomicBreedingCore, GenomicBreedingIO, GenomicBreedingDB, DataFrames, CSV, StatsBase, LibPQ, Dates)
julia> phenomes = simulate_genomes() |>  simulate_trials |> simulate_phenomes;

julia> checkdims(phenomes)
true

julia> isfile("simulated_phenomes.jld2")
true
```
"""
function simulate_phenomes(
    trials::Trials;
    fname_phenomes::String = "simulated_phenomes.jld2",
    overwrite = true,
)::Phenomes
    # genomes = simulate_genomes(); trials = simulate_trials(genomes); trials = trials
    # fname_phenomes::String = "simulated_phenomes.jld2"; overwrite=true
    if isfile(fname_phenomes) && !overwrite
        error("The \"$fname_phenomes\" file exists and overwrite is set to false!")
    end
    if isfile(fname_phenomes) && overwrite
        rm(fname_phenomes)
    end
    phenomes = extractphenomes(trials)
    # tabularise(phenomes)
    GenomicBreedingIO.writejld2(phenomes, fname = fname_phenomes, overwrite = overwrite)
    phenomes
end

"""
    simulate_fit(
        genomes::Genomes,
        phenomes::Phenomes;
        fname_fit::String="simulated_fit.jld2",
        overwrite::Bool=true,
    )::Fit

Generate a simulated genomic prediction model fit from compatible genomic and
phenomic datasets.

This function constructs a synthetic `Fit` object by combining genotype data
from a `Genomes` object with phenotype data from a `Phenomes` object. Marker
effects are randomly generated, genomic estimated values are calculated, model
performance metrics are computed, and the resulting fit is written to a JLD2
file.

The generated fit is intended for testing, examples, benchmarking, and
workflow development rather than statistical inference.

# Arguments

- `genomes::Genomes`:
  A valid genomic dataset containing marker information and allele
  frequencies.
- `phenomes::Phenomes`:
  A valid phenomic dataset containing phenotypic observations corresponding
  to the same entries represented in `genomes`.

# Keyword Arguments

- `fname_fit::String="simulated_fit.jld2"`:
  Output JLD2 filename for the simulated fit.
- `overwrite::Bool=true`:
  Overwrite an existing output file if present.

# Returns

- `"fit"`:
  The simulated `Fit` object.

# Throws

- `ErrorException` if the entries contained in `genomes` and `phenomes`
  do not align exactly.

# Notes

- Missing allele frequencies are replaced with `0.0` before fitting.
- Missing phenotype values are replaced with `0.0`.
- Marker effects (`b_hat`) are randomly sampled and do not represent true
  genetic effects.
- The model is assigned `"OLS"` as its model label, although no ordinary
  least-squares fitting is actually performed.
- Performance metrics are calculated from the simulated predictions and
  should not be interpreted scientifically.

The following metrics are stored in `fit.metrics`:

- `"cor"`: Pearson correlation between observed and predicted values.
- `"rmse"`: Root mean squared error.
- `"r2"`: Coefficient of determination.

# Example

```jldoctest; setup=:(using GenomicBreedingCore, GenomicBreedingIO, GenomicBreedingDB, DataFrames, CSV, StatsBase, LibPQ, Dates)
julia> genomes = simulate_genomes();

julia> phenomes = simulate_trials(genomes) |> simulate_phenomes;

julia> fit = simulate_fit(genomes, phenomes);

julia> checkdims(fit)
true

julia> isfile("simulated_fit.jld2")
true
```
"""
function simulate_fit(
    genomes::Genomes,
    phenomes::Phenomes;
    fname_fit::String = "simulated_fit.jld2",
    overwrite::Bool = true,
)::Fit
    # genomes = simulate_genomes(); trials = simulate_trials(genomes); phenomes = simulate_phenomes(trials); fname_fit::String = "simulated_fit.jld2"; overwrite = true; genomes = genomes; phenomes = sim_phenomes["phenomes"]
    if genomes.entries != phenomes.entries
        error("The Genomes and Phenomes are not compatible, i.e. the entries do not align perfectly!")
    end
    X = genomes.allele_frequencies
    X[ismissing.(X)] .= 0.0
    y = phenomes.phenotypes[:, 1]
    y[ismissing.(y)] .= 0.0
    fit = Fit(n = length(genomes.entries), l = length(genomes.loci_alleles))
    fit.model = "OLS"
    fit.b_hat_labels = genomes.loci_alleles
    fit.b_hat = rand(length(genomes.loci_alleles))
    fit.trait = phenomes.traits[1]
    fit.entries = phenomes.entries
    fit.populations = phenomes.populations
    fit.y_true = y
    fit.y_pred = X * fit.b_hat
    fit.metrics = Dict(
        "cor" => cor(fit.y_true, fit.y_pred),
        "rmse" => mean(sqrt.((fit.y_true - fit.y_pred) .^ 2)),
        "r2" => 1.00 - (var(fit.y_true - fit.y_pred) / var(fit.y_true)),
    )
    GenomicBreedingIO.writejld2(fit, fname = fname_fit, overwrite = overwrite)
    fit
end
